### ISSUE TITLE
Bathroom Remodel Overview

### ISSUE THREAD

**Issue by msimerson** [The-Mountaineers/Stevens-Lodge#1]
### Cast of Characters

- Stevens Lodge
    - Derek Lester - Chair
    - Jessica Smith - Chair
    - Jason Naranjo - Facilities Co-Chair
    - Jeff Bowman - Facilities Co-Chair
- Mountaineers
    - Matt Simerson - VP of Outdoor Centers
    - Rich Johnson - Board Member & Building Contractor
        - Nick - builder

#### April
- [x] #2
- [x] #3

#### May

- [x] Nick comes up on a weekend to estimate his labor portion (T&M)
- [x] #4
- [x] #5

#### June

- [x] Bath: order / procure building materials (Rich)
- [x] Bath: demolish existing bathrooms (Jason)
    - [x] walls and fixtures removed, floor remains (Work Party, June 25-26)
- [x] Bath: get final measurements of the space and update plans (Matt)

#### July

- [x] remove the subfloor (Work Party, July 16, 17)
- [x] bath: buy plumbing materials (Matt, Jason, Rich)
- [x] bath: install plumbing (Matt, Jason)
- [x] #8

#### August

- finish in-wall items
    - [x] bath: buy electrical materials (Jason / contractor)
    - [x] bath: install electrical (Jason)
    - [ ] bath: rough-in plumbing inspection (Matt)
    - [x] bath: spray foam insulate bathroom walls (Matt)
- fabricate bathroom stall walls & doors (Rich, Nick)
- install bathrooms, June 24 to Sep 1  and Oct 1-Nov 20 (Nick)
    - [x] cover walls with 1/2" plywood (framing is 24" OC)
    - [x] paint the plywood with RedGard or equivalent sealing membrane
    - [x] install Dumawall tiles over plywood
    - [x] install bathroom fixtures & stalls
- [ ] bath: spray foam insulate under the floor (Matt)
 
### Considerations

- the current Stevens bathrooms are not nice
- we would like the new bathrooms to be nice.
- do not be constrained by current "overly cozy" layout
    - unisex layout
    - trough sink
- water is very expensive
    - plumb with the ability to integrate future gray water system
- heated cement floor would be nice
- partition walls for bath/stalls.

### Jason's Presentation to Board

- The bathrooms were brought inside Stevens Lodge in 1977. Minor cosmetic and mechanical have been updates since that time.  We have plumbing that is failing and flooring and structural members that are rotting and need replacing. Ventilation and heating the space safely is also an issue that will be addressed by this project.
- Bids: We are in the process of receiving bids. We expect the project to have a total cost of $70-100K. We will be reusing/up cycling our low-flow toilets and urinal. Our goal is to come in at or under $70K. We have one bid for $72K and one bid for  only demolition and rough-in  (framing, structural, and flooring) for $9.5K. 
- Funding request: We are requesting a 60/40 spilt, with the organization carrying 60% of the total cost and Stevens Lodge self supporting and or fundraising 40%. 
- Timeline: We want funding approval by April 1st 2022 so that we can complete fundraising and schedule contractor(s). The project is expected to begin in late June or early July and be done no later than August 1st. This will allow us to open for PCT season.

**Comment by msimerson** [comment]
### Washington State Building Code

Chapters 51-56 WAC, Uniform Plumbing Code

> 402.5 Setting. Fixtures shall be set level and in proper alignment with reference to adjacent walls. No water closet or bidet shall be set closer than fifteen (15) inches (381 mm) from its center to any side wall or obstruction nor closer than thirty (30) inches (762 mm) center to center to any similar fixture. The clear space in front of any water closet or bidet shall be not less than twenty-four (24) inches (610 mm). No urinal shall be set closer than twelve (12) inches (305 mm) from its center to any side wall or partition nor closer than twenty-four (24) inches (610 mm) center to center.

**Comment by msimerson** [comment]
Early design. Will update with actual framing and room dimensions after demolition work has been completed.

[Stevens Bath H.skp.zip](https://github.com/Mountaineers/Stevens-Lodge/files/8704178/Stevens.Bath.H.skp.zip)

**Comment by msimerson** [comment]
Updated model, As-Build.

[Stevens Bath I.skp.zip](https://github.com/Mountaineers/Stevens-Lodge/files/9473962/Stevens.Bath.I.skp.zip)

### Notes

- stalls are 32" from wall centerline to centerline.
- Toilets drains are 32" on center as well.

**Comment by msimerson** [comment]
![IMG_3982](https://user-images.githubusercontent.com/261635/188039150-175438bb-6f32-4574-a0cb-c1ec3c5a3b77.jpeg)

**Comment by msimerson** [comment]
### Jun 25-26
[Jun 25 Work Party](https://www.mountaineers.org/activities/activities/stewardship-stevens-lodge-4), [Jun 26 Work Party](https://www.mountaineers.org/activities/activities/stewardship-stevens-lodge-4-2022-06-26)
- demoed walls, sinks, showers, toilets

### Jul 16
[Jul 16 Work Party](https://www.mountaineers.org/activities/activities/stewardship-stevens-lodge-4-2022-07-16)
- demoed toilet, urinal, electrical, plumbing, floor

### Jul 23
Jeff, Jason
- demoed brick & mortar support for old coal furnace

### Aug 11 & 12
Jeff, Craig (PCT hiker), and Matt accomplished:

- finished tearing out the rotten floor joists
- added pier blocks and another support beam
- framed in the new joists
- laid part of the subfloor
- hauled truckloads of junk down to the dumpster
- added sill and headers for interior walls
- connected a few sections of the new drain pipe

### Aug 19 & 20
Jeff, Kevin (Work Party Volunteer), and Matt accomplished:

- finished the floor framing
- mostly installed the new bath fans
- installed more of the waste stack plumbing (after cleanup)
- added more wall framing
- spray foam filled many gaps & cracks

### Aug 30 & 31
Nick, Jeff, Derek, Jason, Penelope, and Matt accomplished:

- Plumb kitchen hand sink into waste lines
- Plumb 4 floor drains into waste lines
- Lay second layer of 3/4 plywood subfloor
    - drill 2 holes for 3 sinks
- Plumb central waste lines to all 5 toilets
    - drill 5 holes for closet flanges, 12" from finished wall, 12-3/4" from framing
- Install the rest of the plywood flooring
    - screw plywood to the joists every 8"
- Frame 2 walls behind sinks
    - co-planar with existing wall
- Install 1/2" plywood on the perimeter walls
    - only bottom 2' of exterior walls (to permit spray foam addition & electrical rough-ins)
    - along existing section of rough sawn, use 3" screws into joists
- Finish shower wall framing
    - paying careful attention to shower valve install instructions

### TODO

- finish bath fan vent plumbing
    a. crimp the 6" ducting & assemble
    b. install sheet metal screws at joints
    c. seal seams with foil tape
- RedGard coat the floor and 1' up the walls
- add electrical boxes
- Pad and flash the protrusions through the floor
- Lay the remesh for the floor
    - cutting openings around rough-ins with bolt cutters
